apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-jsdn-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-z1r4@sha256:46e57eebf2a45bb8c42c76521af7faa673923bf4ed2073002978a8269ce7bc97
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
